image:
  - Visual Studio 2019

environment:
  matrix:
  # - TOXENV: py27  # end-of-life-branches
  # - TOXENV: py35
  # - TOXENV: py36
  # - TOXENV: py37
  - TOXENV: py310
  - TOXENV: py311
  - TOXENV: py312
  - TOXENV: py313

build: false

install:
  # - py --list
  # - py -m pip install --upgrade pip
  - py -m pip install tox

test_script:
  - py -m tox