image:
  - Visual Studio 2019

environment:
  matrix:
  - TOXENV: py39
  - TOXENV: py310
  - TOXENV: py311
  - TOXENV: py312

build: false

install:
  # - py --list
  # - py -m pip install --upgrade pip
  - py -m pip install tox

test_script:
  - py -m tox